config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "welcome#index"
  resources :users, only: [:new, :create]
  resources :dashboard, only: [:index]
  resources :reminder, only: [:new, :create]

  get "/registration", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, uniqueness: true, presence: true
  validates :email, uniqueness: true, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP } 
  validates_presence_of :password, require: true

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :require_current_user

  def index
    
  end

  def require_current_user
    render file: '/public/401' unless current_user
  end
end

app/controllers/reminder_controller.rb
class ReminderController < ApplicationController
  before_action :require_current_user

  def new;end

  def create
    reminder =  ReminderFacade.new(reminder_params, current_user)
    if reminder.valid?
      flash[:notice] = "Reminder Created!"
      redirect_to :dashboard_index
    else
      flash[:message] = reminder.errors
      render :new
    end
  end

  private

  def require_current_user
    render file: '/public/401' unless current_user
  end

  def reminder_params
    params.permit(:start_date, :end_date, :time, :message)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by(email: params[:email].downcase)

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to dashboard_index_path
    else
      flash[:message] = 'The email or password you entered is incorrect'
      redirect_to root_path
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    new_user = User.new(user_params)
    if new_user.save
      session[:user_id] = new_user.id
      redirect_to dashboard_index_path
    else
      flash[:error] = new_user.errors.full_messages.to_sentence
      @user = User.new
      render :new
    end
  end

  private

  def user_params
    params[:user][:email] = params[:user][:email].downcase
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index;end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/index.html.erb
<h4>Welcome to Reminder, <%=current_user.username%></h4> <br>
<%= button_to 'New Reminder', 'reminder/new', class: "btn btn-warning", method: :get %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReminderMessages</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="nav-bar">
      <% if current_user %>
        <nav class="navbar navbar-light bg-light">
          <a class="navbar-brand" href="#">
            <img src="https://cdn.pixabay.com/photo/2018/02/28/19/04/r-3188833_960_720.png" width="30" height="30" class="d-inline-block align-top" alt="">

          </a>
          <h4><%= button_to 'Logout', logout_path, class: "btn btn-warning", method: :delete %></h4>
        </nav>
      <% end %>
    </header>
    <% flash.each do |type, message| %>
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
      <%= message %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>

    <% end %>
    <%= yield %>
  </body>
</html>

app/views/reminder/new.html.erb
<section class="vh-100" style="background-color: #eee;">
  <div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-lg-12 col-xl-11">
        <div class="card text-black" style="border-radius: 25px;">
          <div class="card-body p-md-5">
            <div class="row justify-content-center">
              <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">

                <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Reminder</p>
                  <%= form_with url: reminder_index_path, local: true do |f| %>
                    <%= f.label :start_date %>
                    <%= f.date_field :start_date, value: Time.now.strftime("%Y-%m-%d") %><br>
                    <%= f.label :end_date %>
                    <%= f.date_field :end_date %><br>
                    <%= f.label 'Reminder Time' %>
                    <%= f.time_field :time %><br>
                    <%= f.text_area :message, size: "50x5" %><br>
                    <%= f.submit 'Create Reminder', class: "btn btn-warning"%>
                  <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/users/new.html.erb
<section class="vh-100" style="background-color: #eee;">
  <div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-lg-12 col-xl-11">
        <div class="card text-black" style="border-radius: 25px;">
          <div class="card-body p-md-5">
            <div class="row justify-content-center">
              <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">

                <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Sign up</p>


                 <%= form_with model: @user, local: true do |f| %>
                  <div class="d-flex flex-row align-items-center mb-4">
                    <div class="form-outline flex-fill mb-0">
                      <%= f.label :username, "Username:", class: "form-label" %>
                      <%= f.text_field :username, class: "form-control" %>
                    </div>
                  </div>

                  <div class="d-flex flex-row align-items-center mb-4">
                    <div class="form-outline flex-fill mb-0">
                      <%= f.label :email, "Email:", class: "form-label" %>
                      <%= f.email_field :email, class: "form-control" %>
                    </div>
                  </div>

                  <div class="d-flex flex-row align-items-center mb-4">
                    <div class="form-outline flex-fill mb-0">
                      <%= f.label :password, "Password:", class: "form-label" %>
                      <%= f.password_field :password, class: "form-control" %>
                    </div>
                  </div>

                  <div class="d-flex flex-row align-items-center mb-4">
                    <div class="form-outline flex-fill mb-0">
                      <%= f.label :reconfirm_password,"Confirm Password:", class: "form-label" %>
                      <%= f.password_field :password_confirmation, class: "form-control" %>
                    </div>
                  </div>

                  <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                    <%= f.submit "Register", class: "btn btn-primary mb-2" %>
                  </div>

                  <% end %>

              </div>
              <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">

                <img src="https://cdn.pixabay.com/photo/2017/06/10/07/32/clock-2389255_960_720.png" class="img-fluid" alt="Sample image">

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/welcome/index.html.erb
<section class="vh-100" style="background-color: #eee;">
  <div class="container mh-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-sm-10">
        <div class="card text-black" style="border-radius: 25px;">
          <div class="card-body p-md-5">
            <div class="row justify-content-center">
              <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">
                <img class="mb-4" src="https://cdn.pixabay.com/photo/2018/02/28/19/04/r-3188833_960_720.png" alt="" width="72" height="72">
                <h1 class="h3 mb-3 font-weight-strong">Welcome to Reminder</h1>
                <p>An app to send reminders</p>
                <% if !current_user %>
                  <%= form_with url: login_path, local: true do |f| %>
                    <%= f.label :email, class: "staticEmail2" %>
                    <%= f.text_field :email, class: "form-control" %><br>
                    <%= f.label :password, class: "inputPassword2" %>
                    <%= f.password_field :password, class: "form-control" %><br>
                    <%= f.submit "Sign In", class: "btn btn-primary mb-2" %><br><br>
                  <% end %>
                  <%= link_to 'New to Reminder? Register Here', '/registration' %>
                <% else %>
                  <%= link_to "Dashboard", dashboard_index_path %>
                <% end %>
              </div>
            </div>
          </div>
      </div>
    </div>
  </div>
</div>